SRC = \
    main.cpp \
    src/app/Application.cpp \
    src/app/ApplicationBootstrap.cpp \
    src/app/ApplicationPhaseController.cpp \
    src/app/GameSession.cpp \
    src/app/GameSessionDebugInfo.cpp \
    src/app/PerfSession.cpp \
    src/config/ApplicationOptions.cpp \
    src/config/CommandLine.cpp \
    src/config/LaunchSettings.cpp \
    src/config/LaunchSettingsMenu.cpp \
    src/platform/ApplicationWindow.cpp \
    src/platform/InputReader.cpp \
    src/platform/PlatformLaunchSupport.cpp \
    src/diagnostics/ApplicationError.cpp \
    src/diagnostics/DebugCrashHandler.cpp \
    src/diagnostics/FramebufferHasher.cpp \
    src/diagnostics/SystemMemoryInfo.cpp \
    src/camera/CameraInput.cpp \
    src/camera/Camera.cpp \
    src/player/PlayerController.cpp \
    src/movement/PlayerMovement.cpp \
    src/physics/PlayerGeometry.cpp \
    src/physics/PlayerGround.cpp \
    src/physics/PlayerCollision.cpp \
    src/spawn/PlayerSpawner.cpp \
    src/interaction/BlockInteractor.cpp \
    src/validators/ApplicationValidator.cpp \
    src/validators/CameraSpeedValidator.cpp \
    src/validators/CollisionValidator.cpp \
    src/validators/BlockEditValidator.cpp \
    src/validators/WorldVisibilityValidator.cpp \
    src/validators/TerrainDeterminismValidator.cpp \
    src/validators/TerrainCaveValidator.cpp \
    src/validators/TerrainConfigValidator.cpp \
    src/validators/WorldRevisionValidator.cpp \
    src/validators/WorldAsyncGenerationValidator.cpp \
    src/validators/WorldScaleValidator.cpp \
    src/policy/RenderDistanceStrategy.cpp \
    src/policy/AdaptiveRenderStrategy.cpp \
    src/policy/FixedRenderStrategy.cpp \
    src/policy/RenderStrategyFactory.cpp \
    src/policy/RenderPolicy.cpp \
    src/render/VoxelRenderer.cpp \
    src/frame/RenderTarget.cpp \
    src/frame/RenderCache.cpp \
    src/frame/RendererColor.cpp \
    src/geometry/ScreenVertex.cpp \
    src/geometry/ClipVertex.cpp \
    src/geometry/TriangleTexture.cpp \
    src/assets/TextureAtlas.cpp \
    src/assets/BlockTextureRegistry.cpp \
    src/assets/BmpImageLoader.cpp \
    src/debug/RenderDebug.cpp \
    src/debug/DebugView.cpp \
    src/debug/DebugOverlayRenderer.cpp \
    src/sky/SkyboxRenderer.cpp \
    src/meshes/MeshClipper.cpp \
    src/meshes/MeshProjector.cpp \
    src/meshes/MeshCuller.cpp \
    src/meshes/TriangleRasterizer.cpp \
    src/meshes/PerspectiveTriangleRasterizer.cpp \
    src/meshes/ChunkMeshRenderer.cpp \
    src/world/World.cpp \
    src/world/WorldGenerationPipeline.cpp \
    src/world/WorldRevisionServer.cpp \
    src/coordinates/WorldCoordinates.cpp \
    src/chunks/WorldChunk.cpp \
    src/chunks/WorldChunkStore.cpp \
    src/chunks/ChunkNeighborMesher.cpp \
    src/chunks/WorldChunkLoader.cpp \
    src/queries/WorldBlockQuery.cpp \
    src/queries/WorldRaycaster.cpp \
    src/edits/WorldEditCommand.cpp \
    src/edits/DeleteBlockCommand.cpp \
    src/edits/PlaceBlockCommand.cpp \
    src/edits/WorldBlockEditor.cpp \
    src/edits/WorldEditHistory.cpp \
    src/entities/EntityState.cpp \
    src/network/ProtocolMessageHeader.cpp \
    src/network/ProtocolJoinMessage.cpp \
    src/network/ProtocolLeaveMessage.cpp \
    src/network/ProtocolChunkRequestMessage.cpp \
    src/network/ProtocolChunkResponseMessage.cpp \
    src/network/ProtocolEditBroadcastMessage.cpp \
    src/network/ProtocolEntityUpdateMessage.cpp \
    src/network/ProtocolChatMessage.cpp \
    src/network/ProtocolPingMessage.cpp \
    src/network/ProtocolPongMessage.cpp \
    src/gpur/GpuChunkMesh.cpp \
    src/gpur/GpuTextureAtlas.cpp \
    src/gpur/GpuMvpBuilder.cpp \
    src/gpur/GlslLoader.cpp \
    src/gpur/GpuWaterBatch.cpp \
    src/gpur/GpuGeometryBatch.cpp \
    src/gpur/GpuOverlayRenderer.cpp \
    src/gpur/GpuSkyRenderer.cpp \
    src/gpur/GpuHudRenderer.cpp \
    src/gpur/GpuWorldRenderer.cpp \
    src/gpur/GpuRenderer.cpp \
    src/font/BitmapFont.cpp \
    src/font/FreeTypeFontBackend.cpp \
    src/font/FontRenderer.cpp \
    src/settings/Settings.cpp \
    src/menu/MenuCanvas.cpp \
    src/menu/MenuScene.cpp \
    src/menu/MenuController.cpp \
    src/menu/MainMenuScene.cpp \
    src/menu/SettingsScene.cpp \
    src/menu/CreditsScene.cpp \
    src/menu/LoadingScene.cpp \
    src/menu/InGameSettingsScene.cpp \

MM_SRC =

TEST_SRC = main.cpp
